# Generated by Django 3.2.10 on 2021-12-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='project_name',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
