# Generated by Django 3.2.10 on 2021-12-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_alter_myproject_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='sub_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
